--Modify EVENT_PAYLOAD Column to BLOB
ALTER TABLE SERVICES_CARD_EVENT
    ADD (
        EVENT_PAYLOAD_BLOB BLOB
        ) LOB (EVENT_PAYLOAD_BLOB) STORE AS EVENT_PAYLOAD_BLOB (TABLESPACE API_SERVICES_CARD_BLOB_DATA);
UPDATE SERVICES_CARD_EVENT SET EVENT_PAYLOAD_BLOB = UTL_RAW.CAST_TO_RAW(EVENT_PAYLOAD);
ALTER TABLE SERVICES_CARD_EVENT DROP COLUMN EVENT_PAYLOAD;
ALTER TABLE SERVICES_CARD_EVENT RENAME COLUMN EVENT_PAYLOAD_BLOB TO EVENT_PAYLOAD;
ALTER TABLE SERVICES_CARD_EVENT
    MODIFY (
        EVENT_PAYLOAD NOT NULL
        );
