ALTER TABLE SERVICES_CARD_INFO DROP COLUMN STREET_ADDRESS;
ALTER TABLE SERVICES_CARD_INFO DROP COLUMN CITY;
ALTER TABLE SERVICES_CARD_INFO DROP COLUMN PROVINCE;
ALTER TABLE SERVICES_CARD_INFO DROP COLUMN COUNTRY;
